package weaver.docs.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-06-21T23:03:26.669+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "DocService", 
                  wsdlLocation = "file:DocService.wsdl",
                  targetNamespace = "http://localhost/services/DocService") 
public class DocService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost/services/DocService", "DocService");
    public final static QName DocServiceHttpPort = new QName("http://localhost/services/DocService", "DocServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:DocService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DocService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:DocService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DocService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns DocServicePortType
     */
    @WebEndpoint(name = "DocServiceHttpPort")
    public DocServicePortType getDocServiceHttpPort() {
        return super.getPort(DocServiceHttpPort, DocServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocServicePortType
     */
    @WebEndpoint(name = "DocServiceHttpPort")
    public DocServicePortType getDocServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(DocServiceHttpPort, DocServicePortType.class, features);
    }

}
