package weaver.docs.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-06-21T23:03:26.625+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://localhost/services/DocService", name = "DocServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface DocServicePortType {

    @WebResult(name = "out", targetNamespace = "http://localhost/services/DocService")
    @RequestWrapper(localName = "createDoc", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.CreateDoc")
    @WebMethod(action = "urn:weaver.docs.webservices.DocService.createDoc")
    @ResponseWrapper(localName = "createDocResponse", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.CreateDocResponse")
    public int createDoc(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/DocService")
        weaver.docs.webservices.DocInfo in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/DocService")
    @RequestWrapper(localName = "getDocCount", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.GetDocCount")
    @WebMethod(action = "urn:weaver.docs.webservices.DocService.getDocCount")
    @ResponseWrapper(localName = "getDocCountResponse", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.GetDocCountResponse")
    public int getDocCount(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/DocService")
    @RequestWrapper(localName = "deleteDoc", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.DeleteDoc")
    @WebMethod(action = "urn:weaver.docs.webservices.DocService.deleteDoc")
    @ResponseWrapper(localName = "deleteDocResponse", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.DeleteDocResponse")
    public int deleteDoc(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/DocService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/DocService")
    @RequestWrapper(localName = "updateDoc", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.UpdateDoc")
    @WebMethod(action = "urn:weaver.docs.webservices.DocService.updateDoc")
    @ResponseWrapper(localName = "updateDocResponse", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.UpdateDocResponse")
    public int updateDoc(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/DocService")
        weaver.docs.webservices.DocInfo in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/DocService")
    @RequestWrapper(localName = "login", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.Login")
    @WebMethod(action = "urn:weaver.docs.webservices.DocService.login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/DocService")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/DocService")
    @RequestWrapper(localName = "getDoc", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.GetDoc")
    @WebMethod(action = "urn:weaver.docs.webservices.DocService.getDoc")
    @ResponseWrapper(localName = "getDocResponse", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.GetDocResponse")
    public weaver.docs.webservices.DocInfo getDoc(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/DocService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/DocService")
    @RequestWrapper(localName = "getList", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.GetList")
    @WebMethod(action = "urn:weaver.docs.webservices.DocService.getList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://localhost/services/DocService", className = "weaver.docs.webservices.GetListResponse")
    public weaver.docs.webservices.ArrayOfDocInfo getList(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/DocService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/DocService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/DocService")
        int in2
    );
}
